---
- name: deploy file .jar
  hosts: "{{ repo_name }}"
  serial: 1

  tasks: 
    - name: get file in the target host
      get_url: 
        url:   http://172.29.16.32:8081/repository/{{ repo_name }}/{{ artifact_name | urlencode }}
        dest: /temp/{{ artifact_name }}
        mode: '0777'
        url_password: password
        url_username: admin
    
    - name: deploy file
      shell: 
        chdir: /temp/
        cmd: webappct deploy {{ project_name }} "{{ artifact_name }}" > /temp/output

    - name: remove downloaded file
      file: 
        path: /temp/{{ artifact_name }}
        state: absent

    - name: check site up
      uri: 
        url: "{{ url }}"
        follow_redirects: all
        method: GET
        status_code: 200, 403
      register: result
      until: (result.status == 200 or result.status == 403)
      retries: 60  # 60 * 2 seconds = 2minutes 
      delay: 2 # Every 2 second
     
    - name: fail
      fail:
